const fs = require('fs')
const inquirer = require('inquirer')
const Intern = require('./lib/Intern')
const Engineer = require('./lib/Engineer')
const Manager = require('./lib/Manager')
const generatePage = require('./src/generatePage')
